
DriveTrains:
  Tank:
    backRightSpeed:
    backLeftSpeed:
    frontRightSpeed:
    frontLeftSpeed:

  Swerve:
    backRightSpeed:
    backLeftSpeed:
    frontRightSpeed:
    frontLeftSpeed:
    backRightAngle:
    backLeftAngle:
    frontRightAngle:
    frontLeftAngle: