compatibility: "minibot"
driveTrain:
  subsystem: "driveTrain"
  description: "All motors used in the drive train live here"
  motors:
    groups:
      - "motors"
    rightMotor:
      channel: 30
      type: "CANTalonSRX"
      inverted: False
    leftMotor:
      channel: 20
      type: "CANTalonSRX"
      inverted: False

speedSections:
  subsystem: "speedSections"
  description: "Speed Sections (tables used to determine speeds based on distances)"
  speedSections:
    groups: "configuredValues"
    TurretTurn:
      - [45, .1]
      - [90, .2]
      - [180, .3]
      - ["End", 1]
    PID:
      TurretTurn:
        P: 0
        I: 0
        D: 0
        SpeedFloor: 0.01

TurretMotor:
  subsystem: "turret"
  description: "motor for turret goes here"
  motors:
    groups:
     - "motors"
    turretMotor:
      channel: 12
      type: "SparkMax"
      inverted: False
      motorType: "kBrushless"