compatibility: "newBot"

system:
  subsystem: "system"
  description: "Contains system wide resources such as one off hardware devices"
  gyro:
    groups: "gyros"
    navx:
      type: "navx"
      method: "spi"

driveTrain:
  subsystem: "driveTrain"
  description: "All motors used in the drive train live here"
  motors:
    groups:
      - "motors"
      - "hardware"
    rightMotor:
      channel: 30
      type: "CANTalonFX"
      inverted: False
      pid:
        kP: 0.001
        kI: 0
        kD: 0
        kF: 0
        controlType: "PercentOutput"
        sensorPhase: True
        kPreScale: 2
        feedbackDevice: "IntegratedSensor"
      currentLimits:
        triggerThresholdCurrent: 60
        triggerThresholdTime: 50
        currentLimit: 40

    rightFollower:
      channel: 31
      masterChannel: 30
      type: "CANTalonFXFollower"
      currentLimits:
        triggerThresholdCurrent: 60
        triggerThresholdTime: 50
        currentLimit: 40
      inverted: False

    leftMotor:
      channel: 20
      type: "CANTalonFX"
      inverted: False
      pid:
        kP: 0.001
        kI: 0
        kD: 0
        kF: 0
        controlType: "PercentOutput"
        sensorPhase: True
        kPreScale: 2
        feedbackDevice: "IntegratedSensor"
      currentLimits:
        triggerThresholdCurrent: 60
        triggerThresholdTime: 50
        currentLimit: 40

    leftFollower:
      channel: 21
      masterChannel: 20
      type: "CANTalonFXFollower"
      currentLimits:
        triggerThresholdCurrent: 60
        triggerThresholdTime: 50
        currentLimit: 40
      inverted: False

hopperMotors:
  subsystem: "hopper"
  description: "All motors used in the hopper live here"
  hopperMotors:
    groups: "motors"

    hopperMotor: #There may be multiple
    # we don't have information on this yet.

intakeMotors:
  intakeMotor:
    groups: "motors"

    intakeMotor:
    # There will probably only be one of these
