pneumatics:
  subsystem: "pneumatics"
  description: "All pneumatics goes here Solenoids should be moved to proper subsystem later"
  compressors:
    groups: "compressors"
    compressor:
      type: "compressor"

  solenoids:
    groups: "solenoids"
    loader:
      type: "doubleSolenoid"
      channel:
        forward: 0
        reverse: 1
        pcm: 1
      default: "kReverse"
