compatibility: "scorpion"
driveTrain:
  subsystem: "driveTrain"
  description: "All motors used in the drive train live here"
  type: "Tank"
  motors:
    groups: "motors"
    FrontRightTankMotor:
      channel: 30
      type: "CANTalonFX"
      inverted: True
      pid:
        controlType: "Velocity"
        feedbackDevice: 1
        kPreScale: 4096
        kP: .01
        kD: 0
        kI: .0000001
        kF: 0
        sensorPhase: True

    BackRightTankMotor:
      channel: 31
      masterChannel: 30
      type: "CANTalonFXFollower"
      inverted: True

    FrontLeftTankMotor:
      channel: 20
      type: "CANTalonFX"
      inverted: True
      pid:
        controlType: "Velocity"
        feedbackDevice: 1
        kPreScale: 4096
        kP: .01
        kD: 0
        kI: .0000001
        kF: 0
        sensorPhase: True

    BackLeftTankMotor:
      channel: 21
      masterChannel: 20
      type: "CANTalonFXFollower"
      inverted: True

loaderMotors:
  subsystem: "loader"
  description: "All motors used in the robot loader mechanism live here for the loader component"
  motors:
    groups: "motors"
    loaderMotor:
      channel: 11
      type: "SparkMax"
      inverted: True
      pid: Null
      motorType: "kBrushed"

    intakeMotor:
      channel: 51
      type: "CANTalonSRX"
      inverted: False
      pid: Null
    
    intakeFollower:
      channel: 50
      masterChannel: 51
      type: "CANTalonSRXFollower"
      inverted: False
      pid: Null

shooterMotors:
  subsystem: "shooter"
  description: "All motors used in the robot shooter mechanism live here for the shooter component"
  motors:
    groups: "motors"
    shooterMotor:
      channel: 52
      type: "SparkMax"
      motorType: "kBrushed"
      inverted: False
      pid: Null