compatibility: "teapot"

system:
  subsystem: "system"
  description: "Contains system wide resources such as one off hardware devices"
  gyro:
    groups: "gyros"
    navx:
      type: "navx"
      method: "spi"

driveTrain:
  subsystem: "driveTrain"
  description: "All motors used in the drive train live here"
  motors:
    groups:
      - "motors"
      - "hardware"
    rightMotor:
      channel: 30
      type: "CANTalonFX"
      inverted: True
      pid:
        kP: 0.001
        kI: 0
        kD: 0
        kF: 0
        controlType: "PercentOutput"
        sensorPhase: True
        kPreScale: 2
        feedbackDevice: "IntegratedSensor"
      currentLimits:
        triggerThresholdCurrent: 60
        triggerThresholdTime: 50
        currentLimit: 40

    rightFollower:
      channel: 31
      masterChannel: 30
      type: "CANTalonFXFollower"
      currentLimits:
        triggerThresholdCurrent: 60
        triggerThresholdTime: 50
        currentLimit: 40
      inverted: True

    leftMotor:
      channel: 20
      type: "CANTalonFX"
      inverted: False
      pid:
        kP: 0.001
        kI: 0
        kD: 0
        kF: 0
        controlType: "PercentOutput"
        sensorPhase: True
        kPreScale: 2
        feedbackDevice: "IntegratedSensor"
      currentLimits:
        triggerThresholdCurrent: 60
        triggerThresholdTime: 50
        currentLimit: 40

    leftFollower:
      channel: 21
      masterChannel: 20
      type: "CANTalonFXFollower"
      currentLimits:
        triggerThresholdCurrent: 60
        triggerThresholdTime: 50
        currentLimit: 40
      inverted: False

hopperMotors:
  subsystem: "hopper"
  description: "All motors used in the hopper live here"
  hopperMotors:
    groups: "motors"
    hopperMotorForeside:
      # This is the forward motor
      channel: 60
      type: "SparkMax"
      motorType: "kBrushless"
      inverted: True
      IdleBrake: True
      pid: Null
      currentLimits:
        freeLimit: 28
        stallLimit: 30
        stallLimitRPM: 100
        secondaryLimit: 25

    hopperMotorBackside:
      # This is the feeder wheel for the shooter
      channel: 61
      type: "SparkMax"
      motorType: "kBrushless"
      inverted: False
      IdleBrake: True
      pid: Null
      currentLimits:
        freeLimit: 28
        stallLimit: 30
        stallLimitRPM: 100
        secondaryLimit: 25

loaderSensors:
  subsystem: "breaksensors"
  description: "All IR break sensors used for the loader live here for the loader/LED component"
  loaderSensors:
    groups: "digitalInput"
    sensor0:
      type: "RIODigitalIn"
      channel: 0
      description: "Loading sensor"
    sensor1:
      type: "RIODigitalIn"
      channel: 1
      description: "Middle sensor"
    sensor2:
      type: "RIODigitalIn"
      channel: 2
      description: "Post-shooting sensor"

intakeMotors:
  subsystem: "intake"
  intakeMotor:
    groups: "motors"

    intakeMotor:
      channel: 51
      type: "CANTalonSRX"
      inverted: False
      pid: Null
      currentLimits:
        absMax: 60
        absMaxTimeMs: 50
        maxNominal: 40

winchMotors:
  subsystem: "winch"
  winchMotors:
    groups: "motors"
    winchMotor:
      channel: 10
      type: "SparkMax"
      inverted: False
      motorType: "kBrushless"

shooterMotors:
  subsystem: "shooter"
  description: "All motors used in the robot shooter mechanism live here for the shooter component"
  shooterMotors:
    groups: "motors"
    shooterMotor1:
      channel: 40
      type: "SparkMax"
      inverted: True
      motorType: "kBrushless"

      pid:
        controlType: "Velocity"
        kP: 0.0004
        kI: 0
        kD: 0
        kF: 0.000175
        feedbackDevice: 1
        kPreScale: 1
        coastOnZero: True

      currentLimits:
        freeLimit: 30
        stallLimit: 30
        stallLimitRPM: 50
        secondaryLimit: 35

    shooterMotor2:
      channel: 41
      type: "SparkMax"
      inverted: False
      motorType: "kBrushless"

      pid:
        controlType: "Velocity"
        kP: 0.0004
        kI: 0
        kD: 0
        kF: 0.000175
        feedbackDevice: 1
        kPreScale: 1
        coastOnZero: True

      currentLimits:
        freeLimit: 30
        stallLimit: 30
        stallLimitRPM: 50
        secondaryLimit: 35

speedSections:
  subsystem: "speedSections"
  description: "Speed Sections (tables used to determine speeds based on distances)"
  speedSections:
    groups: "configuredValues"
    TurretTurn:
      - [10, .05]
      - [30, .08]
      - [90, .13]
      - [180, .17]
      - ["End", .19]
    GoToDist:
      - [36, .3]
      - [12, .25]
      - [8, .2]
      - [5, .15]
    TurnToAngle:
      - [10, .08]
      - [20, .15]
      - [40, .2]
      - ["End", .3]
    PID:
      TurretTurn:
        P: 0.0015
        I: 0.001
        D: 0
        SpeedFloor: 0.01

TurretMotor:
  subsystem: "turret"
  description: "motor for turret goes here"
  motors:
    groups:
     - "motors"
    turretMotor:
      channel: 12
      type: "SparkMax"
      IdleBrake: True
      inverted: True
      motorType: "kBrushless"

pneumatics:
  type: "yaml"
  file: "pneumatics.yml"
